-- Esquema inicial do sistema de venda de ingressos da ICB (Épico 9).
-- Modelo espelha as entidades de domínio (br.com.icb.ingressos.domain) e as
-- máquinas de estado de docs/regrasDeNegocio.md. Nomes de coluna seguem a
-- convenção snake_case do Spring (CamelCaseToUnderscoresNamingStrategy).

create table usuario (
    id            bigint generated by default as identity primary key,
    nome          varchar(255) not null,
    email         varchar(255) not null,
    telefone      varchar(255) not null,
    data_criacao  timestamp(6) not null,
    constraint uk_usuario_email unique (email)
);

create table evento (
    id         bigint generated by default as identity primary key,
    nome       varchar(255)  not null,
    descricao  varchar(2000),
    data_hora  timestamp(6)  not null
);

create table lote (
    id                     bigint generated by default as identity primary key,
    evento_id              bigint         not null references evento (id),
    nome                   varchar(255)   not null,
    preco                  numeric(12, 2) not null,
    quantidade_total       integer        not null,
    quantidade_disponivel  integer        not null,
    constraint ck_lote_quantidade_total check (quantidade_total > 0),
    constraint ck_lote_quantidade_disponivel
        check (quantidade_disponivel >= 0 and quantidade_disponivel <= quantidade_total)
);

create index ix_lote_evento on lote (evento_id);

create table pedido (
    id           bigint generated by default as identity primary key,
    usuario_id   bigint         not null references usuario (id),
    data_pedido  timestamp(6)   not null,
    valor_total  numeric(12, 2) not null,
    status       varchar(20)    not null
);

-- Base do job de expiração de reservas (RF-17): pedidos PENDENTE por data.
create index ix_pedido_status_data on pedido (status, data_pedido);

create table pagamento (
    id                  bigint generated by default as identity primary key,
    pedido_id           bigint         not null references pedido (id),
    valor               numeric(12, 2) not null,
    metodo              varchar(20)    not null,
    data_pagamento      timestamp(6),
    status              varchar(20)    not null,
    referencia_gateway  varchar(255),
    constraint uk_pagamento_referencia_gateway unique (referencia_gateway)
);

create index ix_pagamento_pedido on pagamento (pedido_id);

create table ingresso (
    id         bigint generated by default as identity primary key,
    evento_id  bigint       not null references evento (id),
    lote_id    bigint       not null references lote (id),
    pedido_id  bigint       references pedido (id),
    codigo_qr  varchar(255),
    status     varchar(20)  not null
);

-- Busca do primeiro ingresso DISPONIVEL do lote no fluxo de compra (RF-06).
create index ix_ingresso_lote_status on ingresso (lote_id, status);
-- Lista de inscritos de um evento (RF-25).
create index ix_ingresso_evento_status on ingresso (evento_id, status);
create index ix_ingresso_pedido on ingresso (pedido_id);
